[build]
  publish = "."

[build.environment]
  GIT_LFS_ENABLED = "true"

[[headers]]
  for = "/downloads/*"
  [headers.values]
    Content-Disposition = "attachment"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"

[[headers]]
  for = "/updates/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"

[[headers]]
  for = "/announcements.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache"
